#!/bin/sh

if [ -z "$TOKBOX_API_KEY" ] || [ -z "$TOKBOX_SECRET" ]
then
  export TOKBOX_API_KEY=46191302
  export TOKBOX_SECRET=e077924487e0175ec8d5c9344a3dd050c8120470
fi

if [ -d "storage" ]
then
  rm -rf storage/
fi

php -S localhost:8080 -t web/
